apiVersion: v1
data:
  application.properties: |-
    {{ (.Files.Glob "config/*").AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
    environment: dxl-{{ .Release.Namespace }}-gr
  name: application-config-{{ .Release.Name }}
  namespace: dxl-{{ .Release.Namespace }}-gr
